## Numpy

In [1]:

import numpy as np




In [5]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
arr.ndim

2

In [10]:
arr = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [21]:
arr1= np.zeros([2,4])
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
arr = np.arange(5, dtype=np.float64)

print(arr)
print(arr.ndim)
print(arr.shape)

[0. 1. 2. 3. 4.]
1
(5,)


In [28]:
# string

arr1 = np.array(["Hello", "hi"])
print(arr1)
arr2 = np.array([" xyz", " wax"])
print(arr2)

arr3 = np.add(arr1, arr2)
arr3

['Hello' 'hi']
[' xyz' ' wax']


array(['Hello xyz', 'hi wax'], dtype='<U9')

In [34]:
arrstring = np.char.multiply(np.array(["hello"]), 3)
arrstring

array(['hellohellohello'], dtype='<U15')

In [33]:
arrstring = np.char.lower(np.array(["Hello"]))
print(arrstring)

arrstring = np.char.upper(np.array(["Hello"]))
print(arrstring)

arrstring = np.char.split(np.array(["Hello my world"]), "my")
print(arrstring)

['hello']
['HELLO']
[list(['Hello ', ' world'])]


In [59]:
arr = np.arange(8)
print(arr, arr.shape)
arrsh = arr.reshape(2,2,2)
print(arrsh)

print("\n Dimension: " , arrsh.ndim, arrsh[1])
print(arr.reshape(2,2,2).flatten())
print(arrsh.transpose())

[0 1 2 3 4 5 6 7] (8,)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

 Dimension:  3 [[4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [67]:
a = np.arange(9).reshape(3,3)
b = np.array([10,20,30])
print(np.add(a,b))

[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [72]:
a = np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [81]:
a = np.array([[1,2,3], [4,5,6]])
print(a.sum(axis=1), a)

[ 6 15] [[1 2 3]
 [4 5 6]]


In [82]:
print(np.std(a))

1.707825127659933
